### PR TITLE
Fix crash when `target`(in Value.preserveToString) is undefined

### PR DESCRIPTION
**Pull request by gnh1201**
https://github.com/paulmillr/es6-shim/issues/467

### CODE REVIEW

**Comment by gnh1201** [comment]
```
* typeof(globals.Reflect): object
* typeof(ReflectShims.defineProperty): undefined
overrideNative(globals.Reflect, 'defineProperty', ReflectShims.defineProperty); <-- error
```

This means that `globals.Reflect` variable is going to be `undefined`. 

How can I fix a problem that `ReflectShims.defineProperty` is `undefined`?

**Comment by ljharb** [comment]
Ah - if `Reflect` exists but `Reflect.defineProperty` does not, then that block of code should do branch, and call `defineProperty` versus `overrideNative`.

**Comment by gnh1201** [comment]
Found a better solution.

**Comment by ljharb** [comment]
@gnh1201 what better solution? Is #467 still an issue?

**Pull request closed without merging**
