### PR TITLE
Distinguish Set and Map iterators.

### PR DESCRIPTION
**Pull request by cscott**
Closes: #387

### CODE REVIEW

**Comment by ljharb** [comment]
This seems fine, but we should probably have a test to prevent a regression

**Comment by Xotic750** [comment]
What kind of tests would be needed for this?

**Comment by ljharb** [comment]
@Xotic750 i'd assume something from your report in #387.

Although, I'd expect `Object.getPrototypeOf(new Map().entries()) !== Object.getPrototypeOf(new Set().entries())` to be `true`, and I'm not sure that's the case with the shims.

**Comment by Xotic750** [comment]
https://github.com/paulmillr/es6-shim/pull/437

**Pull request closed without merging**
