### PR TITLE
[Tests] migrate tests to Github Actions

### PR DESCRIPTION
**Pull request by ljharb**
Per https://github.com/ljharb/object.assign/pull/81
> travis-ci's new pricing plan, and its defaults, have caused all my `ljharb` repos to have zero CI whatsoever until December. @travis-ci Support is MIA, so I unfortunately can't rely on it as a service anymore.

### CODE REVIEW

**Comment by paulmillr** [comment]
`Allow all actions` is set

**Comment by ljharb** [comment]
I'm very confused why the PR isn't triggering an actions run :-/

**Comment by ljharb** [comment]
@paulmillr is there an "approve and run" button showing for you on the PR status box?

**Comment by paulmillr** [comment]
@ljharb I think it will only show after the merge

**Comment by ljharb** [comment]
That has not been my experience - pull_request_target workflows behave like that, but most of these are pull_request, and should work immediately.

You can see all the hundreds of PRs I linked to https://github.com/ljharb/object.assign/pull/81 running on the first PR.

**Comment by paulmillr** [comment]
perhaps it depends on repo owner, which is different in your repos. let's try merging it, we can always revert

**Comment by ljharb** [comment]
I'd prefer to hold off; I'm pinging github folks about it.

**Comment by ljharb** [comment]
Figured it out; I had to land at least one action in the default branch first to "enable" actions (which seems like a clear bug).

I'll land this once the tests pass.

**Pull request merged**
