### PR TITLE
update year of Copyright (c)

### PR DESCRIPTION
**Pull request by SerkanSipahi**

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks! Would you mind also updating the copyright year in `es6-shim.js` and `es6-sham.js`?

**Comment by SerkanSipahi** [comment]
i found one more updating file : s6-sham.min.js ! This repro is always maintained. I think it make sense for updating the copyright.

**Comment by SerkanSipahi** [comment]
@ljharb : who has created this repro? the structure is not maintainable ! who, what generated the min/map files, etc? why exists a node_modules directory?  the "pull requests" make not sense at the moment !!! just README.md "pull request" is ok.

**Comment by ljharb** [comment]
@SerkanSipahi `node_modules` exists because that's where npm dependencies are installed, which every JS project uses.  "Pull requests" are a github thing, and I'm not sure what you mean by "doesn't make sense".

The "min.js" files are automatically generated whenever the library is released and published on `npm` - github is just for development, npm is for consumption.

Also, I'm not sure that an out of date copyright year on an actively maintained project qualifies as "terrible" but thanks for your opinion.

**Comment by SerkanSipahi** [comment]
@ljharb what i mean is: i would hold clean the repro. Also, no node_modules folder, no min, map, etc files. If someone get this repro from npm or github it should have a build process where everything( node_modules, min, map, etc ) are auto generated. I hope you know what i mean.

**Pull request closed without merging**
